version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jodb
      POSTGRES_USER: jouser
      POSTGRES_PASSWORD: jopass
    ports:
      - "5433:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
